language: node_js
node_js: node
cache:
  npm: true
jobs:
  include:
    - name: "Build and Push"
      script: 
      - npm run build
      deploy:
        local_dir: .vuepress/dist/
        provider: pages
        skip_cleanup: true
        name: Travis Build Bot
        keep_history: true
        on:
          branch: master
        target_branch: gh-pages
        # committer_from_gh: true
        # allow_empty_commit: true
        token:
          secure: hFz8kntljQg3Q9gNBfUBaJwMdyFhxS1aiBU7R+CvwOvwopk5n7sZdj5TlPxHuq4nJ7Sj8r7uJCF5xtyeAn3EFNoJqswjBn48qiDRSAGskQuCKpReeUnd4ra4ZrU0W7I1Sz59GE8q5a/8B6oFEsF8SEtXfawV7Di1WMesNC3DoAHEj/fxqycnf3Ru3/0SUlELIe4YsSfrog3qqCpyQNtiGF8txa6sUa2Wh3Vx7R/+6WFx2oUc9yRlzcGKeYvGOPkbjJqMR/CNkHyEmKbUyxpar7ZcMo70P3o2gYP0tiJAVyU6Pm3d0i5acI4lh3nnTV4KZSaReJ3ibedbXlDFbIBpxEqtbzolpYtV/5HNO8UEUG+Lh99RuDFdLXDTlAw8e9D4G7AT2ttoc/fjasNWx0A00n39STAOUl1uZy/IKm25O42vCCh/Qx11VH380R6BR3MUMzmvtRTOJVNzFkIh0UhTXY9glhb5eYyBXjd3Mxa1WJCuQQ6zd9lb65N6ZCVkUGETvRctgIDxzuMO53P+99oo3pJJN4IThNqPewnr3+Hi5mh+yEk0AR2Aq707KWx4RUWmGvjxrJ0saBpbYJZ2gVH1bWmqvwKlHmJI018na6DeS9Zkn8Sys4JfPtUQQ4zycZWW3zUHtO+t3wZRXdZ+GeetXf3SEro70hXLWHaI8D4NJy0=
    - name: "Lint"
      script: 
      - npm run lint-ci
    - name: "Spellcheck"
      script: 
      - npm run spellcheck
