language: node_js
node_js: node
cache:
  npm: true
jobs:
  include:
    - name: "Build and Push"
      script: 
      - npm run build
      deploy:
        local_dir: .vuepress/dist/
        provider: pages
        skip_cleanup: true
        name: Travis Build Bot
        keep_history: true
        on:
          branch: master
        target_branch: gh-pages
        # committer_from_gh: true
        # allow_empty_commit: true
        token:
          secure: O94oEHwH361ZfmfNu7tZaDlpP/W39RIFHnD9mHwu5SVkPK9eS8cwFGdeMqvf+NjBbdADj7E4xERWVHME5sd1MiJjfBuY+xYmtByEHxOGDNFjfMsiU4TdzTnl/dXxIWwX4adSK3aUqPHDnl/yhayBuih1AmrwbfOOVe4ATDbCO0vIsl8SoEO/gIjjZyBzgycSAJLPoJYdeuyCg3++be4JKc/H+vjTfmoMNgY1WvMzjuih0xAqSmCzk+DlLRfBCBztmuiRii5QDekN0AE6abYr+7uyvmiq30skeGb+siosYaQ3rg5L+9ht+2Cas3PTVifD11UUKn/jdodQ5r//wA+xwXIZ7aftYTVHj+oaFC4iv5k33seZAunidYoZqYa+8oo1Y410tNmY04rCOlUuG6MzzwevNBJmFQ0A4DNvSdDIRNry3zji/lzuYUdYUSfTMFKVOf5NOarobqakzHcdK6mmZ7pqE8l69k6FsXWr6b96wsWo/ux1P5uGeLYP7bN7P55vCYNtbsQlQQwDSBmQ0nCL0+0maP5kZB/LnYQo9Zl1+iNesvvj/L0wLMSP1pCtz/GyevTenZ6rNViI9ahk58Rxu5Mv3cOyxbk1Eg7iaora6gbCo6KiNhSUBFWJSlcolpJluuSloBh81NL6HnGQkXZazz3LIBG7SLAoZqydiYqn5uc=
    - name: "Lint"
      script: 
      - npm run lint-ci
    - name: "Spellcheck"
      script: 
      - npm run spellcheck
